version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ordermatic
    ports:
      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data
    networks:
      - order-matic-network

volumes:
  db-data:

networks:
    order-matic-network:
        driver: bridge