version: '3.8'

services:
  mongodb-dev:
    image: mongo:4.2.3-bionic
    container_name: mongodb-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ../mongo-entrypoint/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - db-data:/data/db
      - mongoconfig:/data/configdb
    networks:
      - order-matic-network


volumes:
  db-data:
  mongoconfig:

networks:
    order-matic-network:
        driver: bridge